spring.datasource.url=jdbc:postgresql://localhost:5432/casadeportiva_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

server.port=8080

gemini.api.key=AQ.Ab8RN6J_MM-Pd_TUe8zBflVbC69Uf6wCIAMEhIutPkF5b2LyHA
football.api.key=a3f4798afemshbc813be6f2912c1p1d23ffjsn7274ff26f0d8
football.api.host=free-api-live-football-data.p.rapidapi.com

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration